"""empty message

Revision ID: 3e5b3c82ae6e
Revises: 
Create Date: 2026-02-05 20:38:36.816671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e5b3c82ae6e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('text_answer', sa.Text(), nullable=True))
    op.add_column('answers', sa.Column('time_taken', sa.Integer(), nullable=True))
    op.add_column('attempts', sa.Column('status', sa.String(length=20), nullable=True))
    op.add_column('attempts', sa.Column('reissued_for', sa.Integer(), nullable=True))
    op.add_column('groups', sa.Column('color', sa.String(length=7), nullable=True))
    op.add_column('questions', sa.Column('text_input_type', sa.String(length=20), nullable=True))
    op.add_column('questions', sa.Column('correct_text_answer', sa.Text(), nullable=True))
    op.add_column('quizzes', sa.Column('allow_show_answers', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quizzes', 'allow_show_answers')
    op.drop_column('questions', 'correct_text_answer')
    op.drop_column('questions', 'text_input_type')
    op.drop_column('groups', 'color')
    op.drop_column('attempts', 'reissued_for')
    op.drop_column('attempts', 'status')
    op.drop_column('answers', 'time_taken')
    op.drop_column('answers', 'text_answer')
    # ### end Alembic commands ###
