"""manual grading

Revision ID: 720d24695f83
Revises: a80bdf4318aa
Create Date: 2026-02-26 21:31:29.533507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '720d24695f83'
down_revision: Union[str, Sequence[str], None] = 'a80bdf4318aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('manually_graded', sa.Boolean(), nullable=True))
    op.add_column('attempts', sa.Column('needs_manual_grading', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attempts', 'needs_manual_grading')
    op.drop_column('answers', 'manually_graded')
    # ### end Alembic commands ###
