"""empty message

Revision ID: 8e141f037bd5
Revises: 
Create Date: 2026-02-02 03:04:37.701529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e141f037bd5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quizzes', 'allow_change_answers')
    op.drop_column('quizzes', 'show_correct_after')
    op.drop_column('quizzes', 'time_limit_seconds')
    op.drop_column('quizzes', 'show_score_immediately')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizzes', sa.Column('show_score_immediately', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('quizzes', sa.Column('time_limit_seconds', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('quizzes', sa.Column('show_correct_after', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('quizzes', sa.Column('allow_change_answers', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
