"""math column added

Revision ID: a80bdf4318aa
Revises: f2719a74cdda
Create Date: 2026-02-26 18:09:06.599249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a80bdf4318aa'
down_revision: Union[str, Sequence[str], None] = 'f2719a74cdda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizzes', sa.Column('allow_math', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quizzes', 'allow_math')
    # ### end Alembic commands ###
